[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
items_dir   = items
dbs_dir     = dbs

[schedule]
reddit = 0 */6 * * * default reddit -a query="${REDDIT_QUERY:python}" -a limit="${REDDIT_LIMIT:10}"
hotmart = 0 8,20 * * * default hotmart -a query="${HOTMART_QUERY:marketing}" -a limit="${HOTMART_LIMIT:10}"
