[scrapyd]
bind_address = 0.0.0.0
eggs_dir    = eggs
logs_dir    = logs
items_dir   = items
dbs_dir     = dbs

[schedule]
reddit_1 = */30 * * * * scrapper reddit -a query="dating" -a limit=10 -s ROBOTSTXT_OBEY=False
reddit_2 = */30 * * * * scrapper reddit -a query="POA" -a limit=5 -s ROBOTSTXT_OBEY=False
reddit_3 = */30 * * * * scrapper reddit -a query="getting her number" -a limit=5 -s ROBOTSTXT_OBEY=False
reddit_4 = */30 * * * * scrapper reddit -a query="Talking to girls" -a limit=5 -s ROBOTSTXT_OBEY=False
hotmart_1 = 0 8,20 * * * scrapper hotmart -a query="marketing" -a limit=5 -s ROBOTSTXT_OBEY=False
hotmart_2 = 0 8,20 * * * scrapper hotmart -a query="desarrollo web" -a limit=5 -s ROBOTSTXT_OBEY=False
generic_1 = 0 */6 * * * scrapper generic -a url="https://books.toscrape.com" -a type=listing -s ROBOTSTXT_OBEY=False
